baseURL = "https://tatianawasbin.com"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "TatianaWasbin.com"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © TatianaWasbin.com 2025"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/logo.png"

[params.address]
address = "Carlsbad, CA"
email = "wasbintatiana@gmail.com"
openingHours = "Available Monday - Friday, 8am to 6pm PST"
phone = "(949)412-3639"

[params.map]
APIkey = "API_KEY"
latitude = "33.1473268"
longitude = "-117.338676485"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/tatiana-wasbin/"
weight = 2

